spring:
  application:
    name: Arcyriea-Loreverse-Oracle-Backend

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/loreverse_test?createDatabaseIfNotExists=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    mariadb:
      url: jdbc:mariadb://localhost:3308/arcyriea-loreverse-test
      username: root
      password: 123456
      driver-class-name: org.mariadb.jdbc.Driver

    oracle:
      url: jdbc:oracle:thin:@localhost:1521/LOREVERSE_TEST
      username: arcyriea
      password: Nanana1029
      driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://localhost:27017/arcyriea-loreverse
    redis:
      host: localhost
      port: 6379

custom:
  jpa:
    mysql-dialect: org.hibernate.dialect.MySQLDialect
    oracle-dialect: org.hibernate.dialect.OracleDialect
# Custom config for JWT (outside of 'spring')
#jwt:
#  secret: yourSecretKeyHere
#  expirationMs: 3600000       # 1 hour
#  refreshExpirationMs: 86400000 # 24 hours
