spring:
  application:
    name: Arcyriea-Loreverse-Oracle-Backend
  datasource:
    mysql:
      enabled: true
    oracle:
      enabled: true

  # CRITICAL: Disable global JPA and DataSource auto-configuration
  # We will manually configure JPA for each datasource
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  # Existing MongoDB and Redis configurations (not managed by JPA auto-config)
  data:
    mongodb:
      uri: mongodb://localhost:27017/arcyriea-loreverse
    redis:
      host: localhost
      port: 6379

# Custom configurations for multiple datasources
custom:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/loreverse_test?createDatabaseIfNotExists=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect

    mariadb:
      url: jdbc:mariadb://localhost:3308/arcyriea-loreverse-test
      username: root
      password: 123456
      driver-class-name: org.mariadb.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MariaDBDialect

    oracle-adw:
      url: jdbc:oracle:thin:@localhost:1521/LOREVERSE_TEST
      username: arcyriea
      password: Nanana1029
      driver-class-name: oracle.jdbc.OracleDriver
      wallet: false
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.OracleDialect

    oracle-atp:
      url: jdbc:oracle:thin:@localhost:1521/LOREVERSE_TEST
      username: arcyriea
      password: Nanana1029
      driver-class-name: oracle.jdbc.OracleDriver
      wallet: false
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.OracleDialect

# Custom config for JWT (outside of 'spring')
#jwt:
#  secret: yourSecretKeyHere
#  expirationMs: 3600000       # 1 hour
#  refreshExpirationMs: 86400000 # 24 hours
